In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
print(np.__version__)

1.16.5

In [3]:
dataset=pd.read_csv("CKD.csv")

In [4]:
dataset.head(399)

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [5]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [6]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [7]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [8]:
dataset["classification_yes"].value_counts()

1    249
0    150
Name: classification_yes, dtype: int64

In [9]:
indep=dataset[['age','bp','al','su','bgr','bu','sc','sod','pot','hrmo','pc_normal','pcc_present','ba_present','htn_yes','dm_yes','cad_yes','appet_yes','pe_yes','ane_yes']]
dep=dataset['classification_yes']

In [10]:
indep.shape

(399, 19)

In [11]:
dep

0      1
1      1
2      1
3      1
4      1
      ..
394    1
395    1
396    1
397    1
398    0
Name: classification_yes, Length: 399, dtype: uint8

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [15]:
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt','log2'],
              'n_estimators':[10,100]} 



grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1') 
   
# fitting the model for grid search 
grid.fit(X_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             scoring='f1', verbose=3)

In [16]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [17]:
print(grid.best_params_)

{'criterion': 'gini', 'max_features': 'auto', 'n_estimators': 100}

In [18]:
table=pd.DataFrame.from_dict(re)

In [19]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.015626,0.000005,0.003127,0.006254,gini,auto,10,"{'criterion': 'gini', 'max_features': 'auto', ...",0.985075,0.939394,0.952381,0.985075,0.968750,0.966135,0.018047,12
1,0.178122,0.015934,0.018751,0.006250,gini,auto,100,"{'criterion': 'gini', 'max_features': 'auto', ...",1.000000,0.971429,0.984615,0.985075,1.000000,0.988224,0.010792,1
2,0.021873,0.007657,0.006250,0.007654,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.969697,0.970588,0.935484,0.985075,1.000000,0.972169,0.021427,9
3,0.178122,0.007653,0.025002,0.007655,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.985075,0.971429,0.984615,0.970588,1.000000,0.982341,0.010786,4
4,0.018751,0.006250,0.012500,0.006250,gini,log2,10,"{'criterion': 'gini', 'max_features': 'log2', ...",0.937500,0.971429,0.968750,0.985075,0.984615,0.969474,0.017317,11
5,0.168744,0.011693,0.028126,0.006249,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",1.000000,0.971429,0.984615,0.970588,0.985075,0.982341,0.010786,4
6,0.021874,0.007653,0.006250,0.007654,entropy,auto,10,"{'criterion': 'entropy', 'max_features': 'auto...",0.985075,0.971429,0.952381,0.985075,0.955224,0.969837,0.014037,10
7,0.171872,0.000003,0.028126,0.006251,entropy,auto,100,"{'criterion': 'entropy', 'max_features': 'auto...",0.985075,0.971429,0.984615,0.985075,1.000000,0.985239,0.009045,3
8,0.021874,0.007655,0.003125,0.006251,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.985075,0.971429,0.935484,0.985075,0.985075,0.972427,0.019213,8
9,0.181918,0.007655,0.024998,0.007654,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",1.000000,0.971429,0.984615,0.970588,1.000000,0.985326,0.012973,2
10,0.018749,0.006251,0.009376,0.007655,entropy,log2,10,"{'criterion': 'entropy', 'max_features': 'log2...",1.000000,0.956522,0.935484,0.985075,1.000000,0.975416,0.025509,7
11,0.157094,0.000011,0.015629,0.000012,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",0.985075,0.971429,0.984615,0.970588,1.000000,0.982341,0.010786,4

In [20]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'gini', 'max_features': 'auto', 'n_estimators': 100}: 0.9924946382275899

In [21]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[51  0]
 [ 1 81]]

In [22]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99        51
           1       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

In [23]:
table_pr=pd.DataFrame()

In [24]:
print(X_test)

[[-0.37073391 -0.50842064 -0.68384276 ...  0.51639778 -0.52223297
  -0.44519456]
 [ 0.85433499  1.03002255  0.94028379 ... -1.93649167 -0.52223297
  -0.44519456]
 [ 1.03809533 -0.50842064 -0.68384276 ...  0.51639778 -0.52223297
  -0.44519456]
 ...
 [-0.24822702  1.79924415 -0.68384276 ... -1.93649167 -0.52223297
  -0.44519456]
 [-0.03431114 -1.27764223  1.75234707 ...  0.51639778 -0.52223297
  -0.44519456]
 [-1.10577525 -1.27764223 -0.68384276 ...  0.51639778 -0.52223297
  -0.44519456]]

In [25]:
age_input=int(input("Age:"))
bp_input=float(input("BP:"))
al_input=int(input("AL:"))
su_input=float(input("SU:"))
bgr_input=float(input("BGR:"))
bu_input=float(input("BU:"))
sc_input=float(input("SC:"))
sod_input=float(input("SOD:"))
pot_input=float(input("POT:"))
hrmo_input=float(input("HRMO:"))
pc_normal_input=int(input("PC 0 or 1:"))
pcc_present_input=(input("PCC 0 or 1:"))
ba_present_input=(input("BA 0 or 1:"))
htn_yes_input=(input("HTN 0 or 1:"))
dm_yes_input=(input("DM 0 or 1:"))
cad_yes_input=(input("CAD 0 or 1:"))
appet_yes_input=(input("APPET 0 or 1:"))
pe_yes_input=(input("PE 0 or 1:"))
ane_yes_input=(input("ANE 0 or 1:"))

Age:10
BP:70
AL:5
SU:1
BGR:120
BU:50
SC:10
SOD:90
POT:1
HRMO:9
PC 0 or 1:0
PCC 0 or 1:0
BA 0 or 1:0
HTN 0 or 1:0
DM 0 or 1:0
CAD 0 or 1:0
APPET 0 or 1:0
PE 0 or 1:0
ANE 0 or 1:0

Age:25
BP:87
AL:4
SU:5
BGR:150
BU:60
SC:35
SOD:90
POT:4
HRMO:6
PC 0 or 1:0
PCC 0 or 1:0
BA 0 or 1:0
HTN 0 or 1:1
DM 0 or 1:0
CAD 0 or 1:1
APPET 0 or 1:0
PE 0 or 1:1
ANE 0 or 1:1

In [27]:
Future_Prediction=grid.predict([[age_input,bp_input,al_input,su_input,bgr_input,bu_input,sc_input,sod_input,pot_input,hrmo_input,pc_normal_input,pcc_present_input,ba_present_input,htn_yes_input,dm_yes_input,cad_yes_input,appet_yes_input,pe_yes_input,ane_yes_input]])

In [28]:
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]